// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZPvmE19PIxRzOc69lDdRZzCnBkY2ucWY',
    appId: '1:766707217406:web:d6eaad14fb1b16e8be06af',
    messagingSenderId: '766707217406',
    projectId: 'gannaty-f16cc',
    authDomain: 'gannaty-f16cc.firebaseapp.com',
    storageBucket: 'gannaty-f16cc.firebasestorage.app',
    measurementId: 'G-84SDT9Z2DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd_jQb1fjfUImqoEClDnhKbJB6F24HsD4',
    appId: '1:766707217406:android:d9f5e6f91e3ae12abe06af',
    messagingSenderId: '766707217406',
    projectId: 'gannaty-f16cc',
    storageBucket: 'gannaty-f16cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtWGzv_ulDXo-v_CDy_97LeIWdygNwWW0',
    appId: '1:766707217406:ios:e6779ec58f0d226ebe06af',
    messagingSenderId: '766707217406',
    projectId: 'gannaty-f16cc',
    storageBucket: 'gannaty-f16cc.firebasestorage.app',
    iosBundleId: 'com.yourcompound.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtWGzv_ulDXo-v_CDy_97LeIWdygNwWW0',
    appId: '1:766707217406:ios:e6779ec58f0d226ebe06af',
    messagingSenderId: '766707217406',
    projectId: 'gannaty-f16cc',
    storageBucket: 'gannaty-f16cc.firebasestorage.app',
    iosBundleId: 'com.yourcompound.adminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZPvmE19PIxRzOc69lDdRZzCnBkY2ucWY',
    appId: '1:766707217406:web:e681c094fcd004a6be06af',
    messagingSenderId: '766707217406',
    projectId: 'gannaty-f16cc',
    authDomain: 'gannaty-f16cc.firebaseapp.com',
    storageBucket: 'gannaty-f16cc.firebasestorage.app',
    measurementId: 'G-37X9CZ7PZN',
  );
}
